### ISSUE TITLE
SCNG slika

### ISSUE THREAD

**Issue by AnzeSinigoj** [benjaminplayer/ErsFoodForm#1]
Brat nemore bit tako v kotu tista slika ni lih meta dodaj malo vec margina.

**Comment by MajorPh4ntom** [comment]
Se popolnoma strinjam kolega @AnzeSinigoj. @benjaminplayer Priporocam tudi uporabo atributa: cursor. 
LP, Srečno pri izdelavi spletne strani.

**Comment by benjaminplayer** [comment]
> Brat nemore bit tako v kotu tista slika ni lih meta dodaj malo vec margina.

Ne se bat, ceu redesign prihaja ob cca. 01.00

**Comment by benjaminplayer** [comment]
> Se popolnoma strinjam kolega @AnzeSinigoj. @benjaminplayer Priporocam tudi uporabo atributa: cursor. 
> LP, Srečno pri izdelavi spletne strani.

Hvala bom upošteval ;)

**Comment by benjaminplayer** [comment]
> Ne se bat, ceu redesign prihaja ob cca. 01.00
Pu ure gor al dol ahahahhaah
